integrations:
- name: aws-garbage-collector
  resources:
    requests:
        memory: 200Mi
        cpu: 25m
    limits:
      memory: 400Mi
      cpu: 50m
- name: aws-iam-keys
  resources:
    requests:
      memory: 100Mi
      cpu: 15m
    limits:
      memory: 200Mi
      cpu: 25m
  logs: true
- name: github
  resources:
    requests:
      memory: 50Mi
      cpu: 15m
    limits:
      memory: 80Mi
      cpu: 25m
  logs: true
- name: github-repo-invites
  resources:
    requests:
      memory: 50Mi
      cpu: 15m
    limits:
      memory: 150Mi
      cpu: 25m
  logs: true
- name: quay-membership
  resources:
    requests:
      memory: 50Mi
      cpu: 15m
    limits:
      memory: 150Mi
      cpu: 25m
  logs: true
- name: quay-repos
  resources:
    requests:
      memory: 50Mi
      cpu: 15m
    limits:
      memory: 150Mi
      cpu: 25m
  logs: true
- name: github-scanner
  resources:
    requests:
      memory: 500Mi
      cpu: 200m
    limits:
      memory: 1000Mi
      cpu: 400m
  extraArgs: --thread-pool-size 1
  extraEnv:
  - secretName: ${APP_INTERFACE_SQS_SECRET_NAME}
    secretKey: gitlab_pr_submitter_queue_url
- name: aws-support-cases-sos
  resources:
    requests:
      memory: 100Mi
      cpu: 25m
    limits:
      memory: 200Mi
      cpu: 50m
  extraEnv:
  - secretName: ${APP_INTERFACE_SQS_SECRET_NAME}
    secretKey: gitlab_pr_submitter_queue_url
- name: openshift-users
  resources:
    requests:
      memory: 150Mi
      cpu: 20m
    limits:
      memory: 200Mi
      cpu: 40m
  logs: true
- name: openshift-groups
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 300Mi
      cpu: 150m
  logs: true
- name: openshift-namespaces
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 300Mi
      cpu: 200m
  extraArgs: --external
  logs: true
- name: openshift-clusterrolebindings
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 300Mi
      cpu: 150m
  logs: true
- name: openshift-rolebindings
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 400Mi
      cpu: 300m
  logs: true
- name: openshift-network-policies
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  logs: true
- name: openshift-acme
  resources:
    requests:
      memory: 300Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  logs: true
- name: openshift-limitranges
  resources:
    requests:
      memory: 50Mi
      cpu: 100m
    limits:
      memory: 100Mi
      cpu: 150m
- name: openshift-resources
  resources:
    requests:
      memory: 400Mi
      cpu: 600m
    limits:
      memory: 600Mi
      cpu: 1000m
  logs: true
  extraArgs: --external
- name: terraform-resources
  resources:
    requests:
      memory: 800Mi
      cpu: 200m
    limits:
      memory: 1000Mi
      cpu: 400m
  extraArgs: --external --vault-output-path app-sre/integrations-output
- name: terraform-users
  resources:
    requests:
      memory: 1000Mi
      cpu: 200m
    limits:
      memory: 1500Mi
      cpu: 400m
  extraArgs: --io-dir /tmp/throughput/
