excludeService: true
gov_slack: "true"
integrations:
- name: integrations-manager
  resources:
    requests:
      memory: 300Mi
      cpu: 200m
    limits:
      memory: 600Mi
  fluentdResources:
    requests:
      memory: 60Mi
      cpu: 15m
    limits:
      memory: 240Mi
  environmentAware: true
  logs:
    slack: true
    googleChat: true
    slackErrorFilter: true
    govSlack: true
  disableUnleash: true
  unleashConnectionPool: true
  shard_specs:
  - shard_id: 0
    shards: 1
    extra_args: -i quay.io/redhat-services-prod/app-sre-tenant/qontract-reconcile-master/qontract-reconcile-fips-master
