excludeService: true

integrations:
- name: slack-usergroups
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  logs:
    slack: true
- name: openshift-rolebindings
  resources:
    requests:
      memory: 550Mi
      cpu: 100m
    limits:
      memory: 720Mi
      cpu: 200m
  extraArgs: --internal --no-use-jump-host
  logs:
    slack: true
  internalCertificates: true
- name: openshift-clusterrolebindings
  resources:
    requests:
      memory: 350Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 200m
  extraArgs: --internal --no-use-jump-host
  logs:
    slack: true
  internalCertificates: true
- name: openshift-users
  resources:
    requests:
      # Known peaks are at 800Mi
      memory: 800Mi
      cpu: 400m
    limits:
      # Limits 30% above requests
      memory: 1040Mi
      cpu: 500m
  extraArgs: --internal --no-use-jump-host
  logs:
    slack: true
- name: openshift-upgrade-watcher
  resources:
    requests:
      memory: 800Mi
      cpu: 400m
    limits:
      memory: 1040Mi
      cpu: 500m
  extraArgs: --no-use-jump-host
  state: true
- name: openshift-groups
  resources:
    requests:
      # Known peaks are at 600Mi
      memory: 600Mi
      cpu: 200m
    limits:
      # Limits 30% above requests
      memory: 780Mi
      cpu: 300m
  extraArgs: --internal --no-use-jump-host
  logs:
    slack: true
- name: openshift-namespace-labels
  resources:
    requests:
      memory: 600Mi
      cpu: 100m
    limits:
      memory: 800Mi
      cpu: 200m
  extraArgs: --internal
  logs:
    slack: true
  internalCertificates: true
  state: true
- name: openshift-namespaces
  resources:
    requests:
      memory: 600Mi
      cpu: 100m
    limits:
      memory: 800Mi
      cpu: 200m
  extraArgs: --internal --no-use-jump-host
  logs:
    slack: true
  internalCertificates: true
- name: openshift-network-policies
  resources:
    requests:
      memory: 500Mi
      cpu: 150m
    limits:
      memory: 700Mi
      cpu: 250m
  extraArgs: --internal --no-use-jump-host
  logs:
    slack: true
  internalCertificates: true
- name: openshift-limitranges
  resources:
    requests:
      memory: 800Mi
      cpu: 200m
    limits:
      memory: 1040Mi
      cpu: 300m
  extraArgs: --internal --no-use-jump-host
  logs:
    slack: true
- name: openshift-resourcequotas
  resources:
    requests:
      memory: 800Mi
      cpu: 900m
    limits:
      memory: 1200Mi
      cpu: 1200m
  extraArgs: --internal --no-use-jump-host
- name: openshift-resources
  resources:
    requests:
      memory: 1600Mi
      cpu: 900m
    limits:
      memory: 3600Mi
      cpu: 1200m
  extraArgs: --internal --no-use-jump-host
  internalCertificates: true
- name: openshift-vault-secrets
  resources:
    requests:
      memory: 600Mi
      cpu: 200m
    limits:
      memory: 800Mi
      cpu: 400m
  extraArgs: --internal --no-use-jump-host
  internalCertificates: true
- name: openshift-routes
  resources:
    requests:
      # Known peaks are at 770Mi
      memory: 800Mi
      cpu: 200m
    limits:
      # Limits 30% above requests
      memory: 1040Mi
      cpu: 300m
  extraArgs: --internal --no-use-jump-host
- name: openshift-serviceaccount-tokens
  resources:
    requests:
      memory: 800Mi
      cpu: 200m
    limits:
      memory: 1000Mi
      cpu: 400m
  extraArgs: --no-use-jump-host --vault-output-path app-sre/integrations-output
  logs:
    slack: true
  internalCertificates: true
- name: openshift-saas-deploy-trigger-configs
  resources:
    requests:
      memory: 1000Mi
      cpu: 400m
    limits:
      memory: 1200Mi
      cpu: 600m
  extraArgs: --no-use-jump-host
  logs:
    slack: true
  state: true
  shards: 3
  trigger: true
- name: openshift-saas-deploy-trigger-moving-commits
  resources:
    requests:
      memory: 800Mi
      cpu: 400m
    limits:
      memory: 1000Mi
      cpu: 600m
  extraArgs: --no-use-jump-host
  logs:
    slack: true
  state: true
  shards: 5
  trigger: true
- name: openshift-saas-deploy-trigger-upstream-jobs
  resources:
    requests:
      memory: 800Mi
      cpu: 400m
    limits:
      memory: 1000Mi
      cpu: 600m
  extraArgs: --no-use-jump-host
  logs:
    slack: true
  state: true
  shards: 3
  trigger: true
- name: openshift-saas-deploy-trigger-cleaner
  resources:
    requests:
      memory: 800Mi
      cpu: 400m
    limits:
      memory: 1000Mi
      cpu: 600m
  extraArgs: --no-use-jump-host
  logs:
    slack: true
  trigger: true
- name: openshift-tekton-resources
  # resources are tentative for the moment
  resources:
    requests:
      memory: 1500Mi
      cpu: 400m
    limits:
      memory: 1500Mi
      cpu: 600m
  extraArgs: --no-use-jump-host
  logs:
    slack: true
  internalCertificates: true
- name: terraform-resources
  resources:
    requests:
      memory: 800Mi
      cpu: 300m
    limits:
      memory: 1200Mi
      cpu: 600m
  extraArgs: --internal --light --vault-output-path app-sre/integrations-output
  internalCertificates: true
- name: gitlab-projects
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  logs:
    slack: true
- name: gitlab-members
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  logs:
    slack: true
- name: gitlab-permissions
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  logs:
    slack: true
- name: gitlab-owners
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
- name: gitlab-housekeeping
  sleepDurationSecs: 600
  resources:
    requests:
      memory: 300Mi
      cpu: 100m
    limits:
      memory: 600Mi
      cpu: 200m
  extraArgs: --wait-for-pipeline
- name: jenkins-job-builder
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  state: true
  cache: true
- name: jenkins-roles
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  logs:
    slack: true
- name: jenkins-webhooks
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  logs:
    slack: true
  cache: true
- name: jenkins-webhooks-cleaner
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  logs:
    slack: true
- name: gitlab-mr-sqs-consumer
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 400Mi
      cpu: 400m
  extraEnv:
  - secretName: ${APP_INTERFACE_SQS_SECRET_NAME}
    secretKey: gitlab_pr_submitter_queue_url
  extraArgs: ${APP_INTERFACE_PROJECT_ID}
  state: true
- name: status-page-components
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  state: true
cronjobs:
- name: jenkins-job-builds-cleaner
  concurrencyPolicy: "Forbid"
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  # once a hour
  cron: '0 * * * *'
- name: ldap-users
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  extraArgs: ${APP_INTERFACE_PROJECT_ID}
  # once a hour
  cron: '0 * * * *'
- name: dashdotdb-cso
  concurrencyPolicy: Replace
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
    limits:
      memory: 600Mi
      cpu: 200m
  # once every 6 hours
  cron: '0 */6 * * *'
  dashdotdb: true
- name: dashdotdb-dvo
  concurrencyPolicy: Replace
  successfulJobHistoryLimit: 12
  failedJobHistoryLimit: 12
  restartPolicy: Never
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
    limits:
      memory: 600Mi
      cpu: 200m
  # once an hour
  cron: '0 * * * *'
  dashdotdb: true
- name: dashdotdb-slo
  concurrencyPolicy: Replace
  restartPolicy: Never
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
    limits:
      memory: 600Mi
      cpu: 200m
  # once a day
  cron: '0 5 * * *'
  dashdotdb: true
- name: app-interface-reporter
  command: app-interface-reporter
  concurrencyPolicy: Replace
  restartPolicy: Never
  resources:
    requests:
      memory: 400Mi
      cpu: 100m
    limits:
      memory: 600Mi
      cpu: 200m
  # first day of month
  cron: '0 1 1 * *'
  extraEnv:
  - name: XDG_CACHE_HOME
    value: /tmp/.cache
  extraArgs: --gitlab-project-id=${APP_INTERFACE_PROJECT_ID} --reports-path=/tmp/report
- name: create-namespace
  command: e2e-tests
  concurrencyPolicy: Replace
  restartPolicy: Never
  resources:
    requests:
      memory: 300Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  cron: '0 8,20 * * *'
  extraArgs: --thread-pool-size 1
- name: dedicated-admin-rolebindings
  command: e2e-tests
  concurrencyPolicy: Replace
  restartPolicy: Never
  resources:
    requests:
      memory: 300Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  cron: '0 8,20 * * *'
  extraArgs: --thread-pool-size 1
- name: default-project-labels
  command: e2e-tests
  concurrencyPolicy: Replace
  restartPolicy: Never
  resources:
    requests:
      memory: 300Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  cron: '0 8,20 * * *'
  extraArgs: --thread-pool-size 1
- name: default-network-policies
  command: e2e-tests
  concurrencyPolicy: Replace
  restartPolicy: Never
  resources:
    requests:
      memory: 300Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  cron: '0 8,20 * * *'
  extraArgs: --thread-pool-size 1
