integrations:
- name: slack-usergroups
  resources:
    requests:
      memory: 80Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  logs:
    slack: true
- name: openshift-rolebindings
  resources:
    requests:
      memory: 550Mi
      cpu: 100m
    limits:
      memory: 720Mi
      cpu: 200m
  extraArgs: --internal
  logs:
    slack: true
  internalCertificates: true
- name: openshift-clusterrolebindings
  resources:
    requests:
      memory: 350Mi
      cpu: 100m
    limits:
      memory: 500Mi
      cpu: 200m
  extraArgs: --internal
  logs:
    slack: true
  internalCertificates: true
- name: openshift-namespaces
  resources:
    requests:
      memory: 600Mi
      cpu: 100m
    limits:
      memory: 800Mi
      cpu: 200m
  extraArgs: --internal
  logs:
    slack: true
  internalCertificates: true
- name: openshift-network-policies
  resources:
    requests:
      memory: 500Mi
      cpu: 150m
    limits:
      memory: 700Mi
      cpu: 250m
  extraArgs: --internal
  logs:
    slack: true
  internalCertificates: true
- name: openshift-resources
  resources:
    requests:
      memory: 1000Mi
      cpu: 200m
    limits:
      memory: 1200Mi
      cpu: 400m
  extraArgs: --internal
  logs:
    slack: true
  internalCertificates: true
- name: openshift-vault-secrets
  resources:
    requests:
      memory: 600Mi
      cpu: 200m
    limits:
      memory: 800Mi
      cpu: 400m
  extraArgs: --internal
  internalCertificates: true
- name: openshift-serviceaccount-tokens
  resources:
    requests:
      memory: 800Mi
      cpu: 200m
    limits:
      memory: 1000Mi
      cpu: 400m
  extraArgs: --vault-output-path app-sre/integrations-output
  logs:
    slack: true
  internalCertificates: true
- name: openshift-saas-deploy-trigger-configs
  resources:
    requests:
      memory: 600Mi
      cpu: 400m
    limits:
      memory: 800Mi
      cpu: 600m
  extraArgs: --no-use-jump-host
  logs:
    slack: true
  state: true
  shards: 3
- name: openshift-saas-deploy-trigger-moving-commits
  resources:
    requests:
      memory: 600Mi
      cpu: 400m
    limits:
      memory: 800Mi
      cpu: 600m
  extraArgs: --no-use-jump-host
  logs:
    slack: true
  state: true
  shards: 3
- name: openshift-saas-deploy-trigger-upstream-jobs
  resources:
    requests:
      memory: 600Mi
      cpu: 400m
    limits:
      memory: 800Mi
      cpu: 600m
  extraArgs: --no-use-jump-host
  logs:
    slack: true
  state: true
  shards: 3
- name: terraform-resources
  resources:
    requests:
      memory: 800Mi
      cpu: 300m
    limits:
      memory: 1200Mi
      cpu: 600m
  extraArgs: --internal --light --vault-output-path app-sre/integrations-output
  internalCertificates: true
- name: gitlab-projects
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
- name: gitlab-members
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
- name: gitlab-permissions
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
- name: gitlab-integrations
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
- name: gitlab-owners
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
- name: gitlab-housekeeping
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  extraArgs: --wait-for-pipeline
- name: jenkins-job-builder
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  logs:
    cloudwatch: true
  state: true
  cache: true
- name: jenkins-roles
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  logs:
    slack: true
- name: jenkins-webhooks
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  logs:
    slack: true
  cache: true
- name: jenkins-webhooks-cleaner
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  logs:
    slack: true
- name: ldap-users
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  extraArgs: ${APP_INTERFACE_PROJECT_ID}
  logs:
    slack: true
- name: gitlab-mr-sqs-consumer
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 400Mi
      cpu: 400m
  extraEnv:
  - secretName: ${APP_INTERFACE_SQS_SECRET_NAME}
    secretKey: gitlab_pr_submitter_queue_url
  extraArgs: ${APP_INTERFACE_PROJECT_ID}
  state: true
