integrations:
- name: openshift-namespace-labels
  resources:
    requests:
      memory: 800Mi
      cpu: 400m
    limits:
      # Limits 30% above requests
      memory: 1040Mi
      cpu: 500m
  state: true
  logs:
    slack: false
  disableUnleash: true
- name: openshift-namespaces
  resources:
    requests:
      # Known peaks are at 800Mi
      memory: 800Mi
      cpu: 400m
    limits:
      # Limits 30% above requests
      memory: 1040Mi
      cpu: 500m
  logs:
    slack: false
  disableUnleash: true
- name: openshift-network-policies
  resources:
    requests:
      # Known peaks are at 800Mi
      memory: 800Mi
      cpu: 100m
    limits:
      # Limits 30% above requests
      memory: 1040Mi
      cpu: 200m
  logs:
    slack: false
  disableUnleash: true
- name: openshift-resources
  resources:
    requests:
      memory: 1600Mi
      cpu: 900m
    limits:
      memory: 3600Mi
      cpu: 1200m
  logs:
    slack: false
  disableUnleash: true
- name: openshift-routes
  resources:
    requests:
      # Known peaks are at 770Mi
      memory: 800Mi
      cpu: 200m
    limits:
      # Limits 30% above requests
      memory: 1040Mi
      cpu: 300m
  logs:
    slack: false
  disableUnleash: true
- name: openshift-vault-secrets
  resources:
    requests:
      memory: 600Mi
      cpu: 900m
    limits:
      memory: 800Mi
      cpu: 1200m
  logs:
    slack: false
  disableUnleash: true
- name: terraform-aws-route53
  resources:
    requests:
      memory: 500Mi
      cpu: 100m
    limits:
      memory: 1000Mi
      cpu: 500m
  logs:
    slack: false
  disableUnleash: true
- name: terraform-resources
  resources:
    requests:
      memory: 1500Mi
      cpu: 200m
    limits:
      memory: 2000Mi
      cpu: 400m
  logs:
    slack: false
  disableUnleash: true
  extraArgs: --vault-output-path osd-fedramp/integrations-output
- name: terraform-tgw-attachments
  resources:
    requests:
      memory: 2300Mi
      cpu: 400m
    limits:
      memory: 3000Mi
      cpu: 600m
  logs:
    slack: false
  disableUnleash: true
- name: terraform-vpc-peerings
  resources:
    requests:
      memory: 2600Mi
      cpu: 500m
    limits:
      memory: 3200Mi
      cpu: 1400m
  logs:
    slack: false
  disableUnleash: true
- name: jenkins-job-builder
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  state: true
  cache: true
  disableUnleash: true
- name: jenkins-webhooks
  resources:
    requests:
      memory: 100Mi
      cpu: 100m
    limits:
      memory: 200Mi
      cpu: 200m
  cache: true
  logs:
    slack: false
  disableUnleash: true
- name: openshift-saas-deploy-trigger-configs
  resources:
    requests:
      memory: 1000Mi
      cpu: 400m
    limits:
      memory: 1200Mi
      cpu: 600m
  state: true
  shards: 3
  trigger: true
  logs:
    slack: false
  disableUnleash: true
- name: openshift-tekton-resources
  resources:
    requests:
      memory: 1500Mi
      cpu: 400m
    limits:
      memory: 1500Mi
      cpu: 600m
  logs:
    slack: false
  disableUnleash: true
- name: terraform-users
  resources:
    requests:
      memory: 2400Mi
      cpu: 200m
    limits:
      memory: 3000Mi
      cpu: 400m
  extraArgs: --io-dir /tmp/throughput/
  logs:
    slack: false
  disableUnleash: true
- name: gitlab-housekeeping
  sleepDurationSecs: 600
  resources:
    requests:
      memory: 300Mi
      cpu: 100m
    limits:
      memory: 600Mi
      cpu: 200m
  extraArgs: --wait-for-pipeline
  logs:
    slack: false
  disableUnleash: true
- name: openshift-rolebindings
  resources:
    requests:
      memory: 550Mi
      cpu: 100m
    limits:
      memory: 720Mi
      cpu: 200m
  logs:
    slack: false
  disableUnleash: true
- name: openshift-clusterrolebindings
  resources:
    requests:
      memory: 350Mi
      cpu: 100m
    limits:
      memory: 720Mi
      cpu: 200m
  logs:
    slack: false
  disableUnleash: true
cronjobs:
- name: resource-scraper
  resources:
    requests:
      memory: 200Mi
      cpu: 200m
    limits:
      memory: 400Mi
      cpu: 300m
  # once a day at midnight
  cron: '0 0 * * *'
  extraArgs: --namespace-name openshift-sre-token-scraper --resource-kind Secret --vault-output-path osd-fedramp/integrations-output
  disableUnleash: true
